name: add_tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  add-tag:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
      - run: git tag $(cat TAG_NAME)
      - run: git push origin main
